name: 'Azure Pages DevTest'
description: 'SimpleDeploy'
inputs:
  azure_static_web_apps_api_tokena:
    description: 'Azure Static Web Apps Api Token'
    required: true
    default: ''
  actiona:
    description: 'Action to perform'
    required: true
    default: 'upload'
  app_source_locationa:
    description: 'Location of App Source Files to Build'
    required: false
    default: 'app'
  api_source_locationa:
    description: 'Location of Api Source Files to Build'
    required: false
    default: 'api'
  app_artifact_locationa:
    description: 'Location of App Artifacts'
    required: false
    default: '.'
  api_artifact_locationa:
    description: 'Location of Api Artifacts'
    required: false
    default: '.'
  build_timeout_in_minutesa:
    description: 'Time limit of oryx build in minutes'
    required: false
    default: ''
  ignore_missing_api_tokena:
    description: 'Allows the action to continue without azure_static_web_apps_api_token'
    required: false
    default: ''
  repository_urla:
    description: 'The url of the source repository. Default: `github.repository.html_url`'
    required: false
    default: '${{fromJson(github.event_path).repository}}'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    DEPLOYMENT_ACTION: "upload"
    DEPLOYMENT_TOKEN: ${{ inputs.azure_static_web_apps_api_tokena }}
    DEPLOYMENT_PROVIDER: GitHub
    REPOSITORY_BASE: "/"
    REPOSITORY_URL: "https://github.com/BrandonHopcraft/"
    BRANCH: master
